name: E2E Test

on:
  push:
    branches:
      - master
      - release-*
    tags:
      - v*
  workflow_dispatch: { }
  pull_request:
    branches:
      - master
      - release-*

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install tools
        run: |
          sudo apt-get update
          sudo snap install kubectl --classic

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install dependencies
        run: go mod download

      - name: Setup KinD
        run: |
          go install sigs.k8s.io/kind@v0.18.0
          kind delete cluster || true
          kind create cluster
          kubectl apply -f https://raw.githubusercontent.com/openkruise/rollouts/refs/heads/master/config/crd/bases/rollouts.kruise.io_rollouts.yaml

      - name: Run E2E tests
        run: go test -v ./tests/e2e/...